### ISSUE TITLE
File uploader dropzone not showing

### ISSUE THREAD

**Issue by samharrison7** [anomalylabs/files-field_type#11]
The files (and file) field type uploader modal isn't displaying the dropzone for the file as the JS and CSS paths are being output with the app reference being prefixed twice in `core\anomaly\file-field_type\resources\views\upload\index.twig` (as `asset_path` returns a prefixed path and `html_script` / `html_style` is adding the prefix again). Changing these to `asset_scripts` and `asset_styles` works fine, i.e., in  `core\anomaly\file-field_type\resources\views\upload\index.twig`:

![image](https://cloud.githubusercontent.com/assets/3359948/18820592/e24a9c7a-8396-11e6-8fbc-9f6a940bb168.png)

**Comment by RyanThompson** [comment]
Hmm.. sounds like we need to fix a deeper issue then. Ill look into it.

**Comment by RyanThompson** [comment]
Taking this up on the pyro repo
